# General options
debug: false # set logger level to debug
silent: false # set logger level to warning
tcp_port: 53214
show_data: false
tr: 1.0
n_cores: 10 # number of cores for Kalman
mask_path: GMribbon_R4Feed.nii
save_orig: False # save the unprocessed image data

# Preprocessing steps in order
steps:
  - name: EMA
    enabled: true
    save: false

  - name: iGLM
    enabled: true
    save: false

  - name: kalman
    enabled: true
    save: false

  - name: smooth
    enabled: true
    save: false

  - name: snorm
    enabled: true
    save: false


# iGLM Options
iGLM_polort: 2
iGLM_motion: true
discard: 10

# Smoothing options
FWHM: 4.0

# Experiment/GUI Options
no_gui: false
no_proc_chair: false # no crosshair
fullscreen: false
screen: 1
q_path: questions_v1 # path to the questions used for the experiment TODO: FIX

# Testing options
snapshot: false

# Matching options
matching:
  match_method: mask_method
  match_start: 100 # Volume when matching should start
  do_win: true # Activate windowing of individual volumes prior to hit estimation
  hit_wl: 4
  vols_noqa: 45 # Min. number of volumes to wait since end of last QA before declaing a new hit

# Hit options
hits:
  nconsec_vols: 2 # Number of consecutive vols over threshold required for a hit
  hit_method: method01 # Method for deciding hits